### ISSUE TITLE
Check on Windows, esp. file separator behavior

### ISSUE THREAD

**Issue by jalovatt** [jalovatt/scythe#150]

**Comment by woodslanding** [comment]
I'm on windows, so if you have a test, I can run it.

**Comment by jalovatt** [comment]
Nothing specific; mostly I was concerned about using `/` as a file separator, but if the library is working for you then it's probably not an issue.

After further reading, I think separators might just be a problem for scripts that actually run command-line processes since `cmd.exe` does have trouble there.
